services: 
  reactApp:
    container_name: react-container_app
    image: react-container_app
    build:
      context: ./Frontend
    volumes:
      - ./react-container:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  django:     
    image: django-container_app
    container_name: django-container_app
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./django-container:/app
    command: ["./wait-for-it.sh", "-t", "30", "mysql:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - mysql
  

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=secureIntelligence
    volumes:
      - secureIntelligence_data:/data/db
      - ./dumps:/docker-entrypoint-initdb.d:ro
volumes:
  secureIntelligence_data: