# Generated by Django 5.1.1 on 2024-11-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('ID_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion_servicio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ID_Tickets', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('Correo', models.CharField(max_length=255)),
                ('Numero_de_telefono', models.CharField(max_length=255)),
                ('Empresa', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('ID_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.tipo_servicio')),
            ],
        ),
    ]
