# Generated by Django 5.1.1 on 2024-09-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('ID_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion_servicio', models.TextField()),
            ],
        ),
    ]
