# Generated by Django 5.1.1 on 2024-10-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('ID_factura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_suscripcion', models.DateTimeField(blank=True)),
                ('Fecha_finalizacion', models.DateTimeField(blank=True)),
                ('Estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_disponibles',
            fields=[
                ('ID_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('ID_suscripcion', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('ID_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion_servicio', models.TextField()),
            ],
        ),
    ]
