# Generated by Django 5.1.1 on 2024-09-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('ID_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
                ('ID_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.tipo_servicio')),
            ],
        ),
    ]
