# Generated by Django 5.1.1 on 2024-09-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_suscripciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('ID_factura', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_suscripcion', models.DateTimeField(blank=True)),
                ('Fecha_finalizacion', models.DateTimeField(blank=True)),
                ('Estado', models.BooleanField(default=False)),
                ('ID_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.suscripciones')),
            ],
        ),
    ]
