# Generated by Django 5.1.1 on 2024-10-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_tickets'),
        ('Usuarios', '0002_tipo_usuario_id_administrador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ID_suscripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.suscripciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicios_disponibles',
            name='ID_tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.tipo_servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscripciones',
            name='ID_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios_disponibles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscripciones',
            name='ID_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ID_Tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.tipo_servicio'),
            preserve_default=False,
        ),
    ]
