# Generated by Django 5.1.1 on 2024-09-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_factura'),
        ('Usuarios', '0006_usuario_id_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='ID_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleados'),
        ),
    ]
