# Generated by Django 5.1.1 on 2024-10-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_factura_id_suscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='ID_Tipo_servicio',
            new_name='ID_tipo_servicio',
        ),
    ]
