# Generated by Django 5.1.1 on 2024-10-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_rename_id_tipo_servicio_tickets_id_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
