# Generated by Django 5.1.1 on 2024-09-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_servicios_id_empleado'),
        ('Usuarios', '0007_usuario_id_empleado_usuario_id_servicios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicios_disponibles',
        ),
    ]
