# Generated by Django 5.1.1 on 2024-10-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_tickets_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
