# Generated by Django 5.1.1 on 2024-10-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('ID_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Name_company', models.CharField(max_length=250)),
                ('contacto', models.CharField(max_length=80)),
                ('nombre_responsable', models.CharField(max_length=25)),
                ('numero_telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('ID_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('SuperUsuario', models.BooleanField(default=False)),
            ],
        ),
    ]
