# Generated by Django 5.1.1 on 2024-10-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_factura_id_suscripcion_and_more'),
        ('Usuarios', '0002_tipo_usuario_id_administrador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_usuario',
            name='ID_administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.administradores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='Id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ID_servicios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios_disponibles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ID_tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipo_usuario'),
            preserve_default=False,
        ),
    ]
