# Generated by Django 5.1.1 on 2024-09-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_derpatamentos_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('ID_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Name_company', models.CharField(max_length=250)),
                ('contacto', models.CharField(max_length=80)),
                ('nombre_responsable', models.CharField(max_length=25)),
                ('numero_telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Derpatamentos',
            new_name='Departamentos',
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('ID_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_telefono', models.CharField(max_length=40)),
                ('Fecha_contrado', models.DateTimeField(blank=True)),
                ('Fecha_finalizacion', models.DateTimeField(blank=True)),
                ('ID_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.departamentos')),
            ],
        ),
    ]
