# Generated by Django 5.1.1 on 2024-09-26 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ID_tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipo_usuario'),
        ),
    ]
