# Generated by Django 5.1.1 on 2024-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_usuario_id_empleado_usuario_id_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
