# Generated by Django 5.1.1 on 2024-10-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_remove_usuario_id_tipo_usuario_delete_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('ID_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('ID_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.administradores')),
                ('Id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes')),
            ],
        ),
    ]
